# Generated by Django 4.2 on 2023-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('Designation', models.CharField(max_length=250)),
                ('photos', models.ImageField(upload_to='photos/teams')),
                ('facebook_links', models.URLField(max_length=100)),
                ('twitter', models.URLField(max_length=100)),
                ('google_plus', models.URLField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
